# Generated by Django 5.0.6 on 2026-04-17 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_orderstatushistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('creada', 'Creada'), ('aprobada', 'Aprobada'), ('pagada', 'Pagada'), ('entregada', 'Entregada'), ('anulada', 'Anulada')], db_index=True, default='creada', max_length=20),
        ),
    ]
